// This file is automatically generated.
import _1984 from './1984.jpg';
import aBriefHistoryOfHumankind from './A Brief History of Humankind.jpg';
import bajoLaMismaEstrella from './bajolamismaestrella.jpg';
import crimenYCastigo from './Crimen y castigo.jpg';
import elPrincipito from './elprincipito.jpg';
import gabrielGarciaMarquez from './Gabrielgarciamarques.jpg';
import hastaQueElVientoTeDevuelvaLaSonrisa from './Hasta que el viento te devuelva la sonrisa.jpg';
import missKinKnows from './misskinknows.jpg';
import prideAndPrejudice from './Pride and Prejudice.jpg';
import satanas from './satanas.jpg';
import theGreatGatsby from './The Great Gatsby.jpg';
import toKillAMockingbird from './To Kill a Mockingbird.jpg';

export {
  _1984,
  aBriefHistoryOfHumankind,
  bajoLaMismaEstrella,
  crimenYCastigo,
  elPrincipito,
  gabrielGarciaMarquez,
  hastaQueElVientoTeDevuelvaLaSonrisa,
  missKinKnows,
  prideAndPrejudice,
  satanas,
  theGreatGatsby,
  toKillAMockingbird,
};
